package template

import (
	_ "embed"
	"fmt"
)

const (
	regularPerm = 0o666
	// DoNotEditHead added to the beginning of a file to prompt the user not to edit
	DoNotEditHead = "// Code generated by sqlx_gen. DO NOT EDIT."
)

// ModelGen defines a template for model
var ModelGen = fmt.Sprintf(`%s

package {{.pkg}}
{{.imports}}
{{.tableName}}
{{.vars}}
{{.types}}
{{.insert}}
{{.delete}}
{{.update}}
{{.list}}
{{.count}}
`, DoNotEditHead)

//go:embed tpl/import.tpl
var Import string

//go:embed tpl/table-name.tpl
var TableName string

//go:embed tpl/field.tpl
var Field string

//go:embed tpl/insert.tpl
var Insert string

//go:embed tpl/delete.tpl
var Delete string

//go:embed tpl/update.tpl
var Update string

//go:embed tpl/list.tpl
var List string

//go:embed tpl/count.tpl
var Count string

//go:embed tpl/tag.tpl
var Tag string

//go:embed tpl/types.tpl
var Types string

//go:embed tpl/var.tpl
var Var string
